services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: "file:/app/prisma/dev.db"
    command: nodemon --watch . --exec npm run dev
